name: Test Template
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 1 * *'
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: testtemplate
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall cargo-generate
      - name: Generate Template and Test
        run: |
          cargo generate --path .. --name $PROJECT_NAME --define description=description --define repo_url=https://example.com
          d $PROJECT_NAME
          cargo check
