name: Test Template
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 1 * *'
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: testtemplate
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          cache-all-crates: "true"
      - name: Install Cargo Generate
        run: cargo install cargo-generate
      - name: Generate Template and Test
        run: |
          mkdir $PROJECT_NAME
          cd $PROJECT_NAME
          cargo generate --path .. --name $PROJECT_NAME --define description=description --define repo_url=https://example.com
      - run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo check
